---
name: stepn
description: Mobile app.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  location: ^5.0.3
  image_picker:
  geolocator: ^9.0.2
  page_transition: ^2.1.0
  animated_splash_screen: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
